/**
 * HTML report renderer.
 *
 * Produces a single, self-contained HTML document (inline CSS, no external
 * assets) from {@link ReportData}. Designed to be shared as a file artifact —
 * e.g. uploaded by a future GitHub Action. All git-derived strings are escaped.
 */
import type {
  AuthorContribution,
  CommitInfo,
  Hotspot,
  ReportData,
  RepoSummary,
} from '../../core/models/types.js';
import { formatDate, relativeTime } from '../format.js';

/** Escape a string for safe interpolation into HTML text/attributes. */
export function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/** Last path segment of a repo path, used as the report title. */
function repoName(repoPath: string): string {
  const parts = repoPath.split(/[\\/]/).filter(Boolean);
  return parts[parts.length - 1] ?? repoPath;
}

/** Risk tier class name for CSS coloring. */
function riskTier(score: number): string {
  if (score >= 0.66) return 'high';
  if (score >= 0.33) return 'medium';
  return 'low';
}

export function renderHtmlReport(data: ReportData): string {
  const { summary, hotspots, generatedAt } = data;
  const title = `${repoName(summary.repoPath)} — Git Time Machine`;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${escapeHtml(title)}</title>
<style>${STYLES}</style>
</head>
<body>
<main class="container">
  ${renderHeader(summary, generatedAt)}
  ${renderStats(summary)}
  <div class="grid">
    <section class="card">
      <h2>Top Authors</h2>
      ${renderAuthors(summary.topAuthors)}
    </section>
    <section class="card">
      <h2>Recent Commits</h2>
      ${renderCommits(summary.recentCommits)}
    </section>
  </div>
  <section class="card">
    <h2>Hotspots <span class="muted">— ${hotspots.analyzedCommits} commits analyzed</span></h2>
    ${renderHotspots(hotspots.hotspots)}
  </section>
  <footer class="footer">
    Generated by <strong>Git Time Machine</strong> · ${escapeHtml(formatDate(generatedAt))}
  </footer>
</main>
</body>
</html>`;
}

function renderHeader(summary: RepoSummary, generatedAt: string): string {
  return `<header class="header">
    <div>
      <h1>${escapeHtml(repoName(summary.repoPath))}</h1>
      <p class="muted">${escapeHtml(summary.repoPath)}</p>
    </div>
    <div class="header-meta">
      <span class="chip">${escapeHtml(summary.branch)}</span>
      <span class="muted">${escapeHtml(relativeTime(generatedAt))}</span>
    </div>
  </header>`;
}

function renderStats(summary: RepoSummary): string {
  const period = `${formatDate(summary.firstCommitDate)} → ${formatDate(summary.lastCommitDate)}`;
  const cards: Array<[string, string]> = [
    ['Commits', String(summary.totalCommits)],
    ['Authors', String(summary.totalAuthors)],
    ['Tracked files', String(summary.trackedFiles)],
    ['Age (days)', String(summary.ageDays)],
  ];
  const items = cards
    .map(
      ([label, value]) =>
        `<div class="stat"><div class="stat-value">${escapeHtml(value)}</div><div class="stat-label">${escapeHtml(label)}</div></div>`,
    )
    .join('\n      ');
  return `<section class="stats">
      ${items}
    </section>
    <p class="period muted">Active period: ${escapeHtml(period)}</p>`;
}

function renderAuthors(authors: readonly AuthorContribution[]): string {
  if (authors.length === 0) return '<p class="muted">No authors found.</p>';
  const max = Math.max(1, ...authors.map((a) => a.commits));
  const rows = authors
    .map((a) => {
      const width = Math.round((a.commits / max) * 100);
      return `<li>
        <div class="author-row">
          <span class="author-name">${escapeHtml(a.author.name)}</span>
          <span class="muted">${a.commits}</span>
        </div>
        <div class="bar"><div class="bar-fill" style="width:${width}%"></div></div>
      </li>`;
    })
    .join('\n      ');
  return `<ul class="authors">\n      ${rows}\n    </ul>`;
}

function renderCommits(commits: readonly CommitInfo[]): string {
  if (commits.length === 0) return '<p class="muted">No commits found.</p>';
  const rows = commits
    .map(
      (c) => `<li>
        <code class="hash">${escapeHtml(c.shortHash)}</code>
        <span class="subject">${escapeHtml(c.subject)}</span>
        <span class="muted when">${escapeHtml(relativeTime(c.date))}</span>
      </li>`,
    )
    .join('\n      ');
  return `<ul class="commits">\n      ${rows}\n    </ul>`;
}

function renderHotspots(hotspots: readonly Hotspot[]): string {
  if (hotspots.length === 0) return '<p class="muted">No file changes found.</p>';
  const rows = hotspots
    .map((h) => {
      const tier = riskTier(h.riskScore);
      const width = Math.round(h.riskScore * 100);
      return `<tr>
        <td class="risk">
          <div class="risk-bar ${tier}"><div class="risk-fill" style="width:${width}%"></div></div>
          <span class="risk-score">${h.riskScore.toFixed(2)}</span>
        </td>
        <td class="num">${h.commits}</td>
        <td class="num">${h.authors}</td>
        <td class="muted">${escapeHtml(relativeTime(h.lastModified))}</td>
        <td class="path"><code>${escapeHtml(h.path)}</code></td>
      </tr>`;
    })
    .join('\n      ');
  return `<table class="hotspots">
      <thead><tr><th>Risk</th><th class="num">Changes</th><th class="num">Authors</th><th>Last</th><th>File</th></tr></thead>
      <tbody>\n      ${rows}\n      </tbody>
    </table>`;
}

const STYLES = `
:root {
  --bg: #0d1117; --panel: #161b22; --border: #30363d; --text: #e6edf3;
  --muted: #8b949e; --accent: #58a6ff; --green: #3fb950; --yellow: #d29922; --red: #f85149;
  color-scheme: dark;
}
* { box-sizing: border-box; }
body {
  margin: 0; background: var(--bg); color: var(--text);
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  line-height: 1.5;
}
.container { max-width: 980px; margin: 0 auto; padding: 32px 20px 64px; }
.muted { color: var(--muted); font-weight: 400; }
code { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }
.header { display: flex; justify-content: space-between; align-items: flex-start; gap: 16px; flex-wrap: wrap; margin-bottom: 24px; }
.header h1 { margin: 0; font-size: 28px; }
.header p { margin: 4px 0 0; font-size: 13px; word-break: break-all; }
.header-meta { display: flex; align-items: center; gap: 12px; }
.chip { background: rgba(88,166,255,.15); color: var(--accent); border: 1px solid rgba(88,166,255,.4); border-radius: 999px; padding: 2px 12px; font-size: 13px; font-weight: 600; }
.stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin-bottom: 8px; }
.stat { background: var(--panel); border: 1px solid var(--border); border-radius: 10px; padding: 16px; text-align: center; }
.stat-value { font-size: 26px; font-weight: 700; }
.stat-label { font-size: 12px; color: var(--muted); text-transform: uppercase; letter-spacing: .04em; margin-top: 4px; }
.period { font-size: 13px; margin: 8px 0 24px; }
.grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 16px; }
.card { background: var(--panel); border: 1px solid var(--border); border-radius: 10px; padding: 20px; }
.card h2 { margin: 0 0 16px; font-size: 16px; }
ul { list-style: none; margin: 0; padding: 0; }
.authors li { margin-bottom: 12px; }
.author-row { display: flex; justify-content: space-between; font-size: 14px; margin-bottom: 4px; }
.author-name { font-weight: 600; }
.bar { background: rgba(255,255,255,.06); border-radius: 4px; height: 6px; overflow: hidden; }
.bar-fill { background: var(--accent); height: 100%; }
.commits li { display: grid; grid-template-columns: auto 1fr auto; gap: 10px; align-items: baseline; padding: 6px 0; border-bottom: 1px solid var(--border); font-size: 14px; }
.commits li:last-child { border-bottom: none; }
.hash { color: var(--yellow); font-size: 12px; }
.subject { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.when { font-size: 12px; white-space: nowrap; }
table { width: 100%; border-collapse: collapse; font-size: 14px; }
th, td { text-align: left; padding: 8px 10px; border-bottom: 1px solid var(--border); }
th { font-size: 12px; color: var(--muted); text-transform: uppercase; letter-spacing: .04em; }
td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; }
.path code { font-size: 12px; word-break: break-all; }
.risk { display: flex; align-items: center; gap: 8px; min-width: 120px; }
.risk-bar { flex: 1; background: rgba(255,255,255,.06); border-radius: 4px; height: 6px; overflow: hidden; }
.risk-fill { height: 100%; }
.risk-bar.high .risk-fill { background: var(--red); }
.risk-bar.medium .risk-fill { background: var(--yellow); }
.risk-bar.low .risk-fill { background: var(--green); }
.risk-score { font-variant-numeric: tabular-nums; font-size: 12px; color: var(--muted); }
.footer { margin-top: 32px; text-align: center; font-size: 13px; color: var(--muted); }
@media (max-width: 720px) {
  .stats { grid-template-columns: repeat(2, 1fr); }
  .grid { grid-template-columns: 1fr; }
}
`;
