/**
 * HTML report renderer.
 *
 * Produces a single, self-contained HTML document (inline CSS, no external
 * assets) from {@link ReportData}. Designed to be shared as a file artifact —
 * e.g. uploaded by a future GitHub Action. All git-derived strings are escaped.
 */
import type {
  ActivityReport,
  AuthorContribution,
  BusFactorReport,
  CommitInfo,
  CouplingReport,
  Hotspot,
  ReportData,
  RepoSummary,
} from '../../core/models/types.js';
import { formatDate, relativeTime } from '../format.js';

const WEEKDAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

/** Escape a string for safe interpolation into HTML text/attributes. */
export function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/** Last path segment of a repo path, used as the report title. */
function repoName(repoPath: string): string {
  const parts = repoPath.split(/[\\/]/).filter(Boolean);
  return parts[parts.length - 1] ?? repoPath;
}

/** Risk tier class name for CSS coloring. */
function riskTier(score: number): string {
  if (score >= 0.66) return 'high';
  if (score >= 0.33) return 'medium';
  return 'low';
}

export function renderHtmlReport(data: ReportData): string {
  const { summary, hotspots, coupling, busFactor, activity, generatedAt } = data;
  const title = `${repoName(summary.repoPath)} — Git Time Machine`;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${escapeHtml(title)}</title>
<style>${STYLES}</style>
</head>
<body>
<main class="container">
  ${renderHeader(summary, generatedAt)}
  ${renderStats(summary)}
  <div class="grid">
    <section class="card">
      <h2>Top Authors</h2>
      ${renderAuthors(summary.topAuthors)}
    </section>
    <section class="card">
      <h2>Recent Commits</h2>
      ${renderCommits(summary.recentCommits)}
    </section>
  </div>
  <section class="card">
    <h2>Activity <span class="muted">— busiest ${WEEKDAYS[activity.busiestWeekday]} @ ${String(activity.busiestHour).padStart(2, '0')}:00</span></h2>
    ${renderActivity(activity)}
  </section>
  <section class="card">
    <h2>Hotspots <span class="muted">— ${hotspots.analyzedCommits} commits analyzed</span></h2>
    ${renderHotspots(hotspots.hotspots)}
  </section>
  <div class="grid">
    <section class="card">
      <h2>Bus Factor <span class="muted">— ${busFactor.siloedFiles}/${busFactor.totalFiles} siloed</span></h2>
      ${renderBusFactor(busFactor)}
    </section>
    <section class="card">
      <h2>Change Coupling</h2>
      ${renderCoupling(coupling)}
    </section>
  </div>
  <footer class="footer">
    Generated by <strong>Git Time Machine</strong> · ${escapeHtml(formatDate(generatedAt))}
  </footer>
</main>
</body>
</html>`;
}

function renderHeader(summary: RepoSummary, generatedAt: string): string {
  return `<header class="header">
    <div>
      <h1>${escapeHtml(repoName(summary.repoPath))}</h1>
      <p class="muted">${escapeHtml(summary.repoPath)}</p>
    </div>
    <div class="header-meta">
      <span class="chip">${escapeHtml(summary.branch)}</span>
      <span class="muted">${escapeHtml(relativeTime(generatedAt))}</span>
    </div>
  </header>`;
}

function renderStats(summary: RepoSummary): string {
  const period = `${formatDate(summary.firstCommitDate)} → ${formatDate(summary.lastCommitDate)}`;
  const cards: Array<[string, string]> = [
    ['Commits', String(summary.totalCommits)],
    ['Authors', String(summary.totalAuthors)],
    ['Tracked files', String(summary.trackedFiles)],
    ['Age (days)', String(summary.ageDays)],
  ];
  const items = cards
    .map(
      ([label, value]) =>
        `<div class="stat"><div class="stat-value">${escapeHtml(value)}</div><div class="stat-label">${escapeHtml(label)}</div></div>`,
    )
    .join('\n      ');
  return `<section class="stats">
      ${items}
    </section>
    <p class="period muted">Active period: ${escapeHtml(period)}</p>`;
}

function renderAuthors(authors: readonly AuthorContribution[]): string {
  if (authors.length === 0) return '<p class="muted">No authors found.</p>';
  const max = Math.max(1, ...authors.map((a) => a.commits));
  const rows = authors
    .map((a) => {
      const width = Math.round((a.commits / max) * 100);
      return `<li>
        <div class="author-row">
          <span class="author-name">${escapeHtml(a.author.name)}</span>
          <span class="muted">${a.commits}</span>
        </div>
        <div class="bar"><div class="bar-fill" style="width:${width}%"></div></div>
      </li>`;
    })
    .join('\n      ');
  return `<ul class="authors">\n      ${rows}\n    </ul>`;
}

function renderCommits(commits: readonly CommitInfo[]): string {
  if (commits.length === 0) return '<p class="muted">No commits found.</p>';
  const rows = commits
    .map(
      (c) => `<li>
        <code class="hash">${escapeHtml(c.shortHash)}</code>
        <span class="subject">${escapeHtml(c.subject)}</span>
        <span class="muted when">${escapeHtml(relativeTime(c.date))}</span>
      </li>`,
    )
    .join('\n      ');
  return `<ul class="commits">\n      ${rows}\n    </ul>`;
}

function renderHotspots(hotspots: readonly Hotspot[]): string {
  if (hotspots.length === 0) return '<p class="muted">No file changes found.</p>';
  const rows = hotspots
    .map((h) => {
      const tier = riskTier(h.riskScore);
      const width = Math.round(h.riskScore * 100);
      return `<tr>
        <td class="risk">
          <div class="risk-bar ${tier}"><div class="risk-fill" style="width:${width}%"></div></div>
          <span class="risk-score">${h.riskScore.toFixed(2)}</span>
        </td>
        <td class="num">${h.commits}</td>
        <td class="num">${h.authors}</td>
        <td class="muted">${escapeHtml(relativeTime(h.lastModified))}</td>
        <td class="path"><code>${escapeHtml(h.path)}</code></td>
      </tr>`;
    })
    .join('\n      ');
  return `<table class="hotspots">
      <thead><tr><th>Risk</th><th class="num">Changes</th><th class="num">Authors</th><th>Last</th><th>File</th></tr></thead>
      <tbody>\n      ${rows}\n      </tbody>
    </table>`;
}

/** Last two path segments, for compact file labels. */
function shortFile(p: string): string {
  const parts = p.split('/');
  return parts.length <= 2 ? p : `…/${parts.slice(-2).join('/')}`;
}

/** Coupling/risk tier from a 0..1 ratio. */
function ratioTier(value: number): string {
  if (value >= 0.66) return 'high';
  if (value >= 0.33) return 'medium';
  return 'low';
}

function renderActivity(activity: ActivityReport): string {
  if (activity.totalCommits === 0) return '<p class="muted">No commits in range.</p>';

  const maxMonth = Math.max(1, ...activity.byMonth.map((m) => m.count));
  const bars = activity.byMonth
    .map((m) => {
      const h = Math.max(2, Math.round((m.count / maxMonth) * 100));
      return `<div class="mbar"><div class="mbar-fill" style="height:${h}%" title="${escapeHtml(m.month)}: ${m.count} commits"></div></div>`;
    })
    .join('');

  const maxCell = Math.max(1, ...activity.byWeekdayHour.flatMap((row) => [...row]));
  const heat = activity.byWeekdayHour
    .map((row, d) => {
      const cells = row
        .map((c, h) => {
          const op = c === 0 ? 0 : (0.15 + 0.85 * (c / maxCell)).toFixed(2);
          return `<span class="hm" style="background:rgba(63,185,80,${op})" title="${WEEKDAYS[d]} ${String(h).padStart(2, '0')}:00 — ${c}"></span>`;
        })
        .join('');
      return `<div class="hm-row"><span class="hm-label muted">${WEEKDAYS[d]}</span>${cells}</div>`;
    })
    .join('');

  const first = activity.byMonth[0]?.month ?? '';
  const last = activity.byMonth[activity.byMonth.length - 1]?.month ?? '';
  return `<div class="months">${bars}</div>
    <div class="months-axis muted"><span>${escapeHtml(first)}</span><span>${escapeHtml(last)}</span></div>
    <div class="heatmap">${heat}</div>`;
}

function renderBusFactor(report: BusFactorReport): string {
  if (report.files.length === 0) return '<p class="muted">Knowledge is well spread.</p>';
  const rows = report.files
    .map((f) => {
      const pct = Math.round(f.primaryShare * 100);
      const color = f.primaryShare >= 0.9 ? 'var(--red)' : 'var(--yellow)';
      return `<li>
        <div class="author-row"><span class="author-name">${escapeHtml(shortFile(f.path))}</span><span class="muted">${pct}%</span></div>
        <div class="bar"><div class="bar-fill" style="width:${pct}%;background:${color}"></div></div>
        <div class="muted bf-owner">${escapeHtml(f.primaryAuthor.name)} · ${f.commits} changes</div>
      </li>`;
    })
    .join('\n      ');
  return `<ul class="authors">\n      ${rows}\n    </ul>`;
}

function renderCoupling(report: CouplingReport): string {
  if (report.pairs.length === 0) return '<p class="muted">No coupled files found.</p>';
  const rows = report.pairs
    .map((p) => {
      const pct = Math.round(p.coupling * 100);
      const tier = ratioTier(p.coupling);
      return `<tr>
        <td class="risk">
          <div class="risk-bar ${tier}"><div class="risk-fill" style="width:${pct}%"></div></div>
          <span class="risk-score">${pct}%</span>
        </td>
        <td class="num">${p.sharedCommits}</td>
        <td class="path"><code>${escapeHtml(shortFile(p.fileA))}</code> <span class="muted">↔</span> <code>${escapeHtml(shortFile(p.fileB))}</code></td>
      </tr>`;
    })
    .join('\n      ');
  return `<table>
      <thead><tr><th>Coupling</th><th class="num">Shared</th><th>Files</th></tr></thead>
      <tbody>\n      ${rows}\n      </tbody>
    </table>`;
}

const STYLES = `
:root {
  --bg: #0d1117; --panel: #161b22; --border: #30363d; --text: #e6edf3;
  --muted: #8b949e; --accent: #58a6ff; --green: #3fb950; --yellow: #d29922; --red: #f85149;
  color-scheme: dark;
}
* { box-sizing: border-box; }
body {
  margin: 0; background: var(--bg); color: var(--text);
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  line-height: 1.5;
}
.container { max-width: 980px; margin: 0 auto; padding: 32px 20px 64px; }
.muted { color: var(--muted); font-weight: 400; }
code { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }
.header { display: flex; justify-content: space-between; align-items: flex-start; gap: 16px; flex-wrap: wrap; margin-bottom: 24px; }
.header h1 { margin: 0; font-size: 28px; }
.header p { margin: 4px 0 0; font-size: 13px; word-break: break-all; }
.header-meta { display: flex; align-items: center; gap: 12px; }
.chip { background: rgba(88,166,255,.15); color: var(--accent); border: 1px solid rgba(88,166,255,.4); border-radius: 999px; padding: 2px 12px; font-size: 13px; font-weight: 600; }
.stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin-bottom: 8px; }
.stat { background: var(--panel); border: 1px solid var(--border); border-radius: 10px; padding: 16px; text-align: center; }
.stat-value { font-size: 26px; font-weight: 700; }
.stat-label { font-size: 12px; color: var(--muted); text-transform: uppercase; letter-spacing: .04em; margin-top: 4px; }
.period { font-size: 13px; margin: 8px 0 24px; }
.grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 16px; }
.card { background: var(--panel); border: 1px solid var(--border); border-radius: 10px; padding: 20px; }
.card h2 { margin: 0 0 16px; font-size: 16px; }
ul { list-style: none; margin: 0; padding: 0; }
.authors li { margin-bottom: 12px; }
.author-row { display: flex; justify-content: space-between; font-size: 14px; margin-bottom: 4px; }
.author-name { font-weight: 600; }
.bar { background: rgba(255,255,255,.06); border-radius: 4px; height: 6px; overflow: hidden; }
.bar-fill { background: var(--accent); height: 100%; }
.commits li { display: grid; grid-template-columns: auto 1fr auto; gap: 10px; align-items: baseline; padding: 6px 0; border-bottom: 1px solid var(--border); font-size: 14px; }
.commits li:last-child { border-bottom: none; }
.hash { color: var(--yellow); font-size: 12px; }
.subject { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.when { font-size: 12px; white-space: nowrap; }
table { width: 100%; border-collapse: collapse; font-size: 14px; }
th, td { text-align: left; padding: 8px 10px; border-bottom: 1px solid var(--border); }
th { font-size: 12px; color: var(--muted); text-transform: uppercase; letter-spacing: .04em; }
td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; }
.path code { font-size: 12px; word-break: break-all; }
.risk { display: flex; align-items: center; gap: 8px; min-width: 120px; }
.risk-bar { flex: 1; background: rgba(255,255,255,.06); border-radius: 4px; height: 6px; overflow: hidden; }
.risk-fill { height: 100%; }
.risk-bar.high .risk-fill { background: var(--red); }
.risk-bar.medium .risk-fill { background: var(--yellow); }
.risk-bar.low .risk-fill { background: var(--green); }
.risk-score { font-variant-numeric: tabular-nums; font-size: 12px; color: var(--muted); }
.months { display: flex; align-items: flex-end; gap: 2px; height: 80px; }
.mbar { flex: 1; display: flex; align-items: flex-end; height: 100%; }
.mbar-fill { width: 100%; background: var(--accent); border-radius: 2px 2px 0 0; }
.months-axis { display: flex; justify-content: space-between; font-size: 11px; margin-top: 4px; }
.heatmap { margin-top: 16px; display: flex; flex-direction: column; gap: 2px; }
.hm-row { display: flex; align-items: center; gap: 2px; }
.hm-label { width: 32px; font-size: 11px; flex: none; }
.hm { flex: 1; height: 12px; border-radius: 2px; background: rgba(255,255,255,.04); }
.bf-owner { font-size: 12px; margin-top: 2px; }
.footer { margin-top: 32px; text-align: center; font-size: 13px; color: var(--muted); }
@media (max-width: 720px) {
  .stats { grid-template-columns: repeat(2, 1fr); }
  .grid { grid-template-columns: 1fr; }
}
`;
